project_id = "cotfweyhlglpjmgqxwqx"

[functions.get-mapbox-token]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-mapbox-token/index.ts"

[functions.parse-notes]
enabled = true
verify_jwt = true
entrypoint = "./functions/parse-notes/index.ts"

[functions.get-platform-stats]
enabled = true
verify_jwt = false
entrypoint = "./functions/get-platform-stats/index.ts"
