project_id = "cotfweyhlglpjmgqxwqx"

[functions.get-mapbox-token]
enabled = true
verify_jwt = true

[functions.verify-mic]
enabled = true
verify_jwt = false

[functions.parse-notes]
enabled = true
verify_jwt = true

[functions.get-platform-stats]
enabled = true
verify_jwt = false

[functions.parse-mic-data]
enabled = true
verify_jwt = false

[functions.parse-mic-updates]
enabled = true
verify_jwt = true

[functions.refresh-weekly-top-mics]
enabled = true
verify_jwt = false
