-- Close the hole that makes signup sheets unsafe to turn on.
--
-- 20260209032557 added this to open_mics_historical:
--
--   CREATE POLICY "Authenticated users can update public mic info"
--     ON open_mics_historical FOR UPDATE TO authenticated
--     USING (true) WITH CHECK (true);
--
-- Its comment says it "enables community editing like the original Google
-- Sheet". What it actually does is let any signed-in account change any column
-- of any of the 406 rows. Postgres ORs permissive policies, so this one
-- subsumes every narrower policy on the table: "Verified hosts can update
-- their mic info" (20251226213036), "Admins can update all mics"
-- (20260121024807) and "admins_can_update_open_mics" (20260812002910) have had
-- no effect since the day this landed.
--
-- That is bad on its own. It becomes urgent now because slots_enabled and
-- signup_method live on this table. Turning signup sheets on, with this policy
-- in place, means any account can open a signup sheet on a room they have
-- nothing to do with, or close the sheet on a room that is running one
-- tonight. The feature cannot ship over it.
--
-- Dropping it is the whole fix. The three narrower policies are already
-- written, already correct, and take over the moment this is gone:
--
--   * a verified host may update the mic they claimed
--   * an admin may update any mic, by either of the two admin checks this
--     codebase uses (profiles.isadmin, and has_role/is_current_user_admin)
--
-- What this turns off: direct writes to the table by an ordinary signed-in
-- user. Open-mic corrections from the public have a real path now, which is
-- the comment thread on each mic (mic_comments), plus mic_flags and
-- mic_confirmations. A correction becomes a report an admin applies, rather
-- than an anonymous write to live data with no review. /dev-view, which serves
-- an editable spreadsheet of every listing to anyone who finds the URL, stops
-- being able to save for non-admins. That is the point.

DROP POLICY IF EXISTS "Authenticated users can update public mic info"
  ON public.open_mics_historical;
