-- Add open mic entries sourced from @the_secret_mics Instagram post
-- New York Comedy Club: Mon–Fri at 85 E 4th St ($5/5 min, sign-ups 4:30pm)
-- The Pit: Friday at 154 W 29th St ($5/5 min, sign-ups 11pm)

INSERT INTO public.open_mics_historical (
  open_mic,
  day,
  start_time,
  venue_name,
  borough,
  neighborhood,
  location,
  venue_type,
  cost,
  stage_time,
  sign_up_instructions,
  active,
  signup_enabled,
  status,
  frequency,
  signup_method,
  last_verified
) VALUES
  (
    'NY Comedy Club Open Mic',
    'Monday',
    NULL,
    'New York Comedy Club',
    'Manhattan',
    'East Village',
    '85 E 4th St, New York, NY 10003',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 4:30pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  ),
  (
    'NY Comedy Club Open Mic',
    'Tuesday',
    NULL,
    'New York Comedy Club',
    'Manhattan',
    'East Village',
    '85 E 4th St, New York, NY 10003',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 4:30pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  ),
  (
    'NY Comedy Club Open Mic',
    'Wednesday',
    NULL,
    'New York Comedy Club',
    'Manhattan',
    'East Village',
    '85 E 4th St, New York, NY 10003',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 4:30pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  ),
  (
    'NY Comedy Club Open Mic',
    'Thursday',
    NULL,
    'New York Comedy Club',
    'Manhattan',
    'East Village',
    '85 E 4th St, New York, NY 10003',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 4:30pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  ),
  (
    'NY Comedy Club Open Mic',
    'Friday',
    NULL,
    'New York Comedy Club',
    'Manhattan',
    'East Village',
    '85 E 4th St, New York, NY 10003',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 4:30pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  ),
  (
    'The Pit Open Mic',
    'Friday',
    NULL,
    'The Pit',
    'Manhattan',
    'Chelsea',
    '154 W 29th St, New York, NY 10001',
    'Comedy Club',
    '$5',
    '5 minutes',
    'Sign-ups open at 11pm in person',
    true,
    false,
    'trial',
    'weekly',
    'in_person',
    '2026-04-14'
  );
