-- Add No Nazar Cafe open mic (Comediq-hosted, Tuesday 6:00 PM, East Village)
INSERT INTO public.open_mics_historical (
  unique_identifier, open_mic, day, start_time, latest_end_time,
  venue_name, borough, neighborhood, location, city, venue_type,
  cost, stage_time, sign_up_instructions, hosts_organizers,
  other_rules, changes_updates, status, active, signup_enabled,
  frequency, signup_method, signup_url, cover_image_url,
  legacy_tag, slot_duration_minutes, slots_enabled, price_per_slot,
  sms_response, verification_count, last_verified, submission_date,
  frequency_custom_text, creator_id
) VALUES (
  gen_random_uuid(),
  'No Nazar Cafe Open Mic',
  'Tuesday',
  '6:00 PM',
  NULL,
  'No Nazar Cafe',
  'Manhattan',
  'East Village',
  '280 E 10th St, New York, NY 10009',
  'New York',
  'Coffee Shop',
  '$5',
  '5 min',
  'Sign up on Comediq or in person',
  'Comediq',
  NULL,
  NULL,
  'verified',
  true,
  true,
  'weekly',
  'comediq_slots',
  NULL,
  NULL,
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  0,
  CURRENT_DATE,
  CURRENT_DATE,
  NULL,
  NULL
);
