
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvpediqable.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cGVkaXFhYmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzOTI1NzAsImV4cCI6MjA0ODk2ODU3MH0.CZOSZj_pC7ZP2iBiJdU0_9ZE5KfN2oShqRt1U8JmDfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
