// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cotfweyhlglpjmgqxwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdGZ3ZXlobGdscGptZ3F4d3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDU0OTEsImV4cCI6MjA2NDIyMTQ5MX0.cgAtNE4qE4dgeHUu_Q1yQEJBimQlDoy8yDDC_if8GuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);